@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes addPatientCommand;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([Patient not found)
    :Add Patient to UniquePatientList
    in AddressBook;

else ([Patient found]))
    : CommandException;
endif
stop
@enduml
